# Generated by Django 5.2.15 on 2026-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
