# Generated by Django 5.2.15 on 2026-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_host_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
