# Generated by Django 5.2.15 on 2026-06-15 08:10

from django.db import migrations, models


def sync_status_from_is_active(apps, schema_editor):
    Participant = apps.get_model("rooms", "Participant")
    Participant.objects.filter(is_active=False).update(status="LEFT")


def restore_is_active_from_status(apps, schema_editor):
    Participant = apps.get_model("rooms", "Participant")
    Participant.objects.filter(status="LEFT").update(is_active=False)
    Participant.objects.exclude(status="LEFT").update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_participant_is_active_participant_left_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("AWAY", "Away"), ("LEFT", "Left")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_status_from_is_active, restore_is_active_from_status),
    ]
