# Generated by Django 5.2.15 on 2026-06-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_participant_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundSkipVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_skip_votes",
                        to="rooms.participant",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skip_votes",
                        to="rooms.gameround",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round", "participant"),
                        name="unique_round_participant_skip_vote",
                    )
                ],
            },
        ),
    ]
