# Generated by Django 5.2.15 on 2026-06-15 08:32

import django.db.models.deletion
from django.db import migrations, models


def sync_existing_acceptance(apps, schema_editor):
    AnswerSubmission = apps.get_model("rooms", "AnswerSubmission")
    AnswerSubmission.objects.filter(is_correct=True).update(is_accepted=True)


def reset_existing_acceptance(apps, schema_editor):
    AnswerSubmission = apps.get_model("rooms", "AnswerSubmission")
    AnswerSubmission.objects.update(is_accepted=False)


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_roundskipvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundAnswerFieldState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[("title", "Title"), ("artist", "Artist")],
                        max_length=20,
                    ),
                ),
                ("first_correct_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["round", "field_type"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="answersubmission",
            name="unique_round_participant_submission",
        ),
        migrations.AddField(
            model_name="answersubmission",
            name="answer_type",
            field=models.CharField(
                choices=[("title", "Title"), ("artist", "Artist"), ("full", "Full")],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="answersubmission",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(sync_existing_acceptance, reset_existing_acceptance),
        migrations.AddField(
            model_name="roundanswerfieldstate",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_fields",
                to="rooms.gameround",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundanswerfieldstate",
            constraint=models.UniqueConstraint(
                fields=("round", "field_type"),
                name="unique_round_answer_field_state",
            ),
        ),
    ]
