# Generated by Django 5.2.15 on 2026-06-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_roundanswerfieldstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ["room", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="rooms.roomteam",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomteam",
            constraint=models.UniqueConstraint(
                fields=("room", "order"),
                name="unique_room_team_order",
            ),
        ),
    ]
