# Generated by Django 5.2.15 on 2026-06-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomteam_participant_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='first_round_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
