# Generated by Django 5.2.15 on 2026-06-15 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_review', 'Request review'), ('disable', 'Disable')], max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
