# Generated by Django 5.2.15 on 2026-06-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('artist_type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='catalog.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('circle', 'Circle')], max_length=30)),
                ('chart_type', models.CharField(choices=[('digital_yearly', 'Digital yearly'), ('digital_monthly', 'Digital monthly'), ('digital_weekly', 'Digital weekly')], max_length=50)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'chart_type', 'year'), name='unique_chart_source_type_year')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('isrc', models.CharField(blank=True, db_index=True, max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.album')),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='catalog.artist')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('channel_title', models.CharField(max_length=255)),
                ('channel_id', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('official_score', models.PositiveSmallIntegerField(default=0)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('auto_approved', 'Auto approved'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('reject_reason', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_candidates', to='catalog.track')),
            ],
            options={
                'ordering': ['-official_score', '-view_count', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('title_raw', models.CharField(max_length=255)),
                ('artist_raw', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.chart')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_entries', to='catalog.track')),
            ],
            options={
                'ordering': ['chart', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('chart', 'rank'), name='unique_chart_entry_rank')],
            },
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('featured', 'Featured'), ('composer', 'Composer'), ('lyricist', 'Lyricist'), ('producer', 'Producer')], default='primary', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_links', to='catalog.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_links', to='catalog.track')),
            ],
            options={
                'ordering': ['track', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('track', 'artist', 'role'), name='unique_track_artist_role')],
            },
        ),
        migrations.CreateModel(
            name='TrackExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('spotify', 'Spotify'), ('musicbrainz', 'MusicBrainz'), ('youtube', 'YouTube'), ('circle', 'Circle')], max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='catalog.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_track_external_provider_id')],
            },
        ),
    ]
