# Generated by Django 5.2.15 on 2026-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chart',
            name='unique_chart_source_type_year',
        ),
        migrations.AddField(
            model_name='chart',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('digital_yearly', 'Digital yearly'), ('digital_monthly', 'Digital monthly'), ('digital_weekly', 'Digital weekly'), ('singing_room_weekly', 'Singing room weekly'), ('download_weekly', 'Download weekly'), ('bgm_weekly', 'BGM weekly'), ('v_coloring_weekly', 'V coloring weekly'), ('bell_weekly', 'Bell weekly'), ('ring_weekly', 'Ring weekly'), ('streaming_weekly', 'Streaming weekly'), ('global_kpop_weekly', 'Global K-pop weekly')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(condition=models.Q(('week__isnull', True)), fields=('source', 'chart_type', 'year'), name='unique_chart_source_type_year_no_week'),
        ),
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(condition=models.Q(('week__isnull', False)), fields=('source', 'chart_type', 'year', 'week'), name='unique_chart_source_type_year_week'),
        ),
    ]
