# Generated by Django 5.2.15 on 2026-06-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('audio', 'Audio')], default='audio', max_length=20)),
                ('start_time_seconds', models.PositiveSmallIntegerField(default=60)),
                ('play_duration_seconds', models.PositiveSmallIntegerField(default=20)),
                ('answer_title', models.CharField(max_length=255)),
                ('answer_artist', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('disabled', 'Disabled')], default='draft', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chart_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='catalog.chartentry')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.track')),
                ('youtube_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.youtubecandidate')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_questions', to='quizzes.quizpack')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_packs', to='quizzes.quizquestion')),
            ],
            options={
                'ordering': ['pack', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('pack', 'question'), name='unique_pack_question')],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('title', 'Title'), ('artist', 'Artist'), ('full', 'Full')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='quizzes.quizquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question', 'answer_type', 'normalized_value'), name='unique_question_answer_alias')],
            },
        ),
    ]
