# Generated by Django 5.2.15 on 2026-06-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_rawcandidate_raw_source_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('b', 'Public chart sample')], max_length=30)),
                ('raw_artist', models.CharField(max_length=255)),
                ('raw_artist_key', models.CharField(db_index=True, max_length=255)),
                ('display_artist', models.CharField(max_length=255)),
                ('first_observed_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('first_observed_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_observed_sample_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_observed_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('last_observed_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_observed_sample_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observed_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('youtube_searched', 'YouTube searched'), ('review_required', 'Review required'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('youtube_search_attempt_count', models.PositiveIntegerField(default=0)),
                ('last_youtube_search_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_seeds', to='ingestion.ingestionjob')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-observed_count'], name='ingestion_a_status_8ef043_idx'), models.Index(fields=['source_type', 'raw_artist_key'], name='ingestion_a_source__29948f_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'raw_artist_key'), name='unique_artist_seed_source_artist_key')],
            },
        ),
    ]
