# Generated by Django 5.2.15 on 2026-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_artistseed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artistseed',
            name='ingestion_a_status_8ef043_idx',
        ),
        migrations.AddField(
            model_name='artistseed',
            name='observed_sample_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='artistseed',
            name='observed_weight_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='artistseed',
            index=models.Index(fields=['status', '-observed_weight_score', '-observed_count'], name='ingestion_a_status_9d2772_idx'),
        ),
    ]
